### ISSUE TITLE
Define grid reinforcement methodology

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#13]
## Todos

- [x] Choose a methodology
- [x] Describe it implementation-ready

## Description of methology

@jochenbuehler: please describe methodology here or link to a description

**Comment by jochenbuehler** [comment]
@birgits, @nesnoj and I have decided to implement the grid extension methodology according to: 
http://um.baden-wuerttemberg.de/fileadmin/redaktion/m-um/intern/Dateien/Dokumente/5_Energie/Versorgungssicherheit/170413_Verteilnetzstudie_BW.pdf

The other two Options would have been:

https://shop.dena.de/fileadmin/denashop/media/Downloads_Dateien/esd/9100_dena-Verteilnetzstudie_Abschlussbericht.pdf

and

https://mueef.rlp.de/fileadmin/mulewf/Themen/Energie_und_Strahlenschutz/Energie/Verteilnetzstudie_RLP.pdf
These are not only the only known studies where the MV as well LV grid extension options are discussed. These are also the only studies where MV grid extension options are described.

The reasons for the taken decision are:
- The methodology seems more realistic than the one described in the Verteilnetzstudie_RLP.pdf. In the Verteilnetzstudie_RLP for example no parallel cables are used in the medium voltage networks.
- Neither the Verteilnetzstudie_RLP nor the DENA-Verteilnetzstudie explains in detail how to proceed if the mentioned grid extension options do not solve over-loading or over-voltage problems. In the Verteilnetzstudie_BW study this is different
- No additional HV/MV- and MV/LV-substations are built according to this methodology. This simplifies the implementation in eGo
- The grid extension methodology is identical for the MV and LV level. This simplifies the implementation in eGo
- Prof Rehtanz is the author of the study. Since he is also the author of the DENA studies the source is reliable

**Comment by birgits** [comment]
@jochenbuehler and I decided to slightly change the methodology used in the Verteilnetzstudie Baden-Württemberg as follows:
* consider LV and MV together
* solve overloading problems before overvoltage problems

Since we have all the information for low and medium voltage we decided to do the grid extension for both voltage levels together (only 10% criterion) instead of using separate voltage range criteria. This led to the thought that instead of first solving voltage problems (as done in the BW study) which would lead to a massive grid expansion in the low voltage grids we first solve overloading problems which might already solve overvoltage problems and therefore lead to less grid expansion. In the DENA-Verteilnetzstudie overloading problems are also solved first (see p. 92).

**Comment by birgits** [comment]
> This led to the thought that instead of first solving voltage problems (as done in the BW study) which would lead to a massive grid expansion in the low voltage grids we first solve overloading problems which might already solve overvoltage problems and therefore lead to less grid expansion.

@gplssm and I talked about this today and it occured to us that when first solving over-loading problems and afterwards over-voltage problems there could theoretically be new over-loading problems. We decided to recheck for over-loading issues after all over-voltage problems are solved. Another thing we need to keep in mind is that some lines that were expanded due to over-loading problems might be over-sized after solving over-voltage problems since in some cases lines are disconnected and a new line is build connected directly to the transformer. However, the overestimation of costs will probably be smaller when first solving over-loading issues since over-voltage will cause much more grid expansion.

**Comment by birgits** [comment]
@jochenbuehler and I also decided to only install underground cables since overhead lines are not usually installed anymore. This is not specified in the BW study though. It says that if a parallel line of the same kind is sufficient to solve over-loading problems this measure is taken, otherwise as many parallel standard lines as needed are installed. In our grid expansion methodology we will only install a parallel line of the same kind as the old line if it's already an underground cable.

**Comment by gplssm** [comment]
I think you already resolved this issue. When the methodology is document [here](https://github.com/openego/eDisGo/blob/93e5bd3cfebe8a766183e37605994ad735193dab/doc/features_in_detail.rst) the issue can be closed.

**Comment by gplssm** [comment]
We can try to include it already in v0.0.1. Otherwise, later ;-)

**Comment by birgits** [comment]
First draft is pushed to features/storage-integration2. Calculation of costs needs to be added.

**Comment by birgits** [comment]
I added the documentation of the calculation of grid expansion costs and will close this issue now.
