### ISSUE TITLE
Define basic structure of Results class and provide dummy data for grid reinforcement

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#14]
The Results class is used to hold data of power flow analysis, grid reinforcement, storage positioning and operation, etc.. 
For example power flow results of a specific run with the id `<id>` shall be accessible from arbitrary nodes. Thus a use case could look like

```
from edisgo.network.results import Results
...
<somehow-retrieve-the-results>
....

voltage_at_node1 = Results(node1, <id>)
```

**Things to consider/Questions**
* There could be multiple power flow runs and of course multiple reinforcement steps iteratively. Enable the user to keep track of these
* @jochenbuehler do we want to reinforce the grid separately in MV and LV or do we analyze zhe grid as a whole?

**Comment by jochenbuehler** [comment]
We should analyze the gird as a whole, since we have the mesurement values for both volgae levels (LV and MV)

**Comment by gplssm** [comment]
Short discussion with @birgits gave new information:

The Results class is used to store information about current and voltage levels before and after grid reinforcement. This can be realized with a DataFrame similarly to the DataFrame returned by PyPSA.
Secondly, the Results class holds information about changes of the cable, line, transformer, etc. type. This information is partially attached to each node/edge, but only the current cable type - regardless if it was reinforced or not. Information management about the changes has to be done in the Results class.

**Comment by gplssm** [comment]
The results management in the Results-object follows a threefold procedure

1. the stack `Results.measure` (basically a simple list with the latest item at the end) provides a history of measures performed in the grid (curtailment, increasing hosting capacity with batteries, grid reinforcement)
2. The DataFrame `Results.pfa_nodes` and `Results.pfa_edges` hold power flow analysis results from several runs. Each run corresponds to and is indexed by an item of the stack `Results.measure`
3. Another DataFrame `Results.equiment_changes` tracks changes in the equipment (replaced or added cable, batteries added, curtailment set to a generator). This is indexed by the components (nodes or edges) and have following columns

equipment: detailing what was changed (line, battery, curtailment). For ease of referencing we take the component itself. For lines we take the line-dict, for batteries the battery-object itself and for curtailment either a dict providing the details of curtailment or a curtailment object if this makes more sense (has to be defined).
change: {added | removed} - says if something was added or removed

**Comment by birgits** [comment]
Does point 1 (measure) provide any more information than point 3 (equipment_changes)?

**Comment by gplssm** [comment]
> Does point 1 (measure) provide any more information than point 3 (equipment_changes)?

Only the order in which measures took place

**Comment by gplssm** [comment]
> Does point 1 (measure) provide any more information than point 3 (equipment_changes)?

Only the order in which measures took place

**Comment by birgits** [comment]
* As discussed I adapted the results object to hold pfa_p, pfa_q and pfa_v_mag_pu instead of pfa_nodes and pfa_edges; I also changed the docstring to say that only results of the last iteration step are stored (instead of results of all iteration step) as we said that only the last  step is relevant (except for maybe debugging purposes)
* Some discussion concerning the p,q and v_mag_pu results also took/takes place in [#7](https://github.com/openego/eDisGo/issues/7) - stations will appear in all three result dataframes; p and q will probably hold the max of p/q0 and p/q1 from pypsa results
* I thought about the measures and equipment_changes attributes again and would suggest a (multiindex) dataframe combining these two plus adding the iteration step. Then we could keep track of what changes took place in which iteration step. But maybe this as well is only interesting when debugging and irrelevant afterwards.
* I would also suggest adding the possibility to add metadata to the object where we could keep track for example for which time period the pfa with batteries was conducted for or which case or timestep we chose to calculate grid expansion.

**Comment by birgits** [comment]
I will also add definitions/placeholders to calculate apparent power and grid expansion costs.

**Comment by gplssm** [comment]
Thanks for your suggestions and implementations! I like! 

Just one question/comment:

> I thought about the measures and equipment_changes attributes again and would suggest a (multiindex) dataframe combining these two plus adding the iteration step. Then we could keep track of what changes took place in which iteration step. But maybe this as well is only interesting when debugging and irrelevant afterwards.

Means you will remove the attribute `measures`? I would suggest to not remove it, because we can use it to keep track of the order measures where performed.

**Comment by birgits** [comment]
We didn't specify it yet so when reinforcing a station I will write the new transformer to the equipment changes dataframe. @gplssm just let me know if you disagree!

**Comment by gplssm** [comment]
The basic structure of the class is available now. Further development is to be discussed elsewhere
