### ISSUE TITLE
Implement grid reinforcement method

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#15]
_this is first just a placeholder/reminder, @birgits use it to add memos to yourself_

**Comment by gplssm** [comment]
Iteratively resolving grid issues works quite well in the MV grid. The LV grid reinforce [runs into an error](https://pastebin.com/ny4ACLUi)

**Comment by birgits** [comment]
Grid reinforcement seems to work so I'll close this issue.

**Comment by nesnoj** [comment]
:tada: Yea, cheers! :tada:

**Comment by nesnoj** [comment]
I have to reopen this one:

@birgits Currently, you do reinforcement for open rings (I sould better say closed rings ;) but they'll be opened [soon](https://github.com/openego/eDisGo/issues/23#issuecomment-335106705)) under **normal operation conditions**.

Not implemented are the **faulty conditions**, where a ring is fed by one side only. It is described in the [DINGO paper](http://reiner-lemoine-institut.de/wp-content/publications/20171004_JPCS/SciGRID_Conference_2017_DINGO_Jonathan_Amme_preprint.pdf), p 9 (2). For this case, different thresholds for max. voltage drop and line loading apply (cf. paper). 
We have to consider this case.

**Comment by birgits** [comment]
We decided that for now faulty conditions will not be analysed in grid expansion because:
* We only add new generators and only analyse feedin case. There is no guideline saying that connection of new generators needs to be designed for faulty conditions (in the case of disruptions generators can be curtailed). See mail from andreas kirchner from LVN: 

> Hierzu gibt es keine Richtlinie. Das einzige was in einer Richtlinie steht und passen würde ist, dass die EE-Anlagen nicht n-1-sicher angeschlossen werden. D.h. die Anlagen werden nur für den ungestörten Netzbetrieb (also Normalschaltzustand) berechnet.

* New connections of loads need to be designed for faulty conditions. As there are no additional loads considered in the ego project and grids from dingo are already designed for faulty conditions where the open ring is fed by one side only (as described in dingo paper) it is currently not relevant.

* DENA and BW study do not analyse faulty conditions. 

We keep this issue open as a reminder.

**Comment by birgits** [comment]
This ticket serves as a reminder and is not relevant for v0.0.1 I would say. I would change the milestone if you agree @gplssm. There is no fitting milestone though, since it is not just nice to have but necessary when we add new loads (e.g. in egon project). Maybe we leave the milestone open.

**Comment by birgits** [comment]
n-1 security is tackled in #202. I'll therefore close this issue.
