### ISSUE TITLE
dir and config files for edisgo

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#25]
We need a general solution for an eDisGo-directory and config files.
Several discussions took place in dingo: https://github.com/openego/ding0/issues/177, https://github.com/openego/ding0/issues/181.

**eDisGo-dir**
In https://github.com/openego/ding0/issues/177 @gplssm proposed to create dir in the setup process. However, if the package is cloned (and not installed) these dirs would not be created. This is why I prefer the [solution used by oemof](https://github.com/oemof/oemof/blob/b27b72af7f7e5e6cd4c745f92a78e18b07a91721/oemof/tools/helpers.py): dir(s) are created at runtime as soon as they are requested.

My suggestion:
- dir-structure:
```
~/.edisgo/
~/.edisgo/log/
~/.edisgo/config/
~/.edisgo/output/
...
```
These paths are either hard-coded or part of a separate (internal) config.
As a better and more standardized solution, we could use something like `~/.ego/edisgo/...`, `~/.ego/dingo/...`.
- As soon as the base dir `~./edisgo` or one of its subdirs is requested, check if it exists. If not, create it.

**Config**
- Dir: `~/.edisgo/config/`
- Different from dingo, we use only 1 config file
- Again, we use configparser
- Ship default config file(s) with eDisGo. When a config file is requested (config section requested, [example from dingo](https://github.com/openego/ding0/blob/58df5c263541a242001f53b0aae59cef9c41f461/ding0/core/__init__.py#L876)), check if it's there. If not, copy default config file(s).
- DB config: Use ego.io's DB config, see https://github.com/openego/ego.io/pull/24 (@gplssm, is it ready-to-use after merging?) and https://github.com/openego/ego.io/issues/16.
Nice-to-have: If the entry cannot be found, the user can create a new entry which is stored in the ego.io DB config.
- consider 3. from https://github.com/openego/ding0/issues/177

**Comment by gplssm** [comment]
Regarding the call to create directory structure and copy default config files you are right. If someone clones the repo and executes a script those won't be available. But consider another case: someone only uses parts of eDisGo. A realistic case is the package `ego`. This package will import some parts of the eDisGo API. Thus, we have to make sure that in all single functions that can be used individually, the check for the existence of `~/.edisgo` is included. To conclude, we can move the place where the config dir is created, but I don't know to which location. 

Regarding the structure I'm fine. We extend it on demand. For example, where would you put data files?
The filenames and structure of subdirectories could either be hard-coded in a `dict` somewhere top-level in the package (in order to make it accessible to the whole package) or stored in a package-internal config file that is copied to `site-packages`. 

I would use more than one config file. For the moment I would separate "technical config" from "assumptions/parameters". The latter is more intended to be changed by the user.

The connection provider https://github.com/openego/ego.io/pull/24 should be ready for merge. Actually, I don't know anymore why we haven't finalized. Probably lack of time. I would suggest to give it a try using the feature branch.

**Comment by nesnoj** [comment]
Thanks for your review! (I added numbers)
1. I like the oemof solution where [`get_basic_path()`](https://github.com/oemof/oemof/blob/b27b72af7f7e5e6cd4c745f92a78e18b07a91721/oemof/tools/helpers.py#L11) is used everywhere to access the config. It checks for existance every time when it's called. We could just add the file copy mechanism here.
2. I prefer the second solution (store it in a package-internal config file)
3. Ok
4. I'll give it a try

**Comment by nesnoj** [comment]
Merged and tested. Please re-open if needed..

**Comment by nesnoj** [comment]
We have to restructure the config files, e.g.

- merge configs `data` and `db_tables`
- there's no clear distinction between `scenario` <-> `costs`, `flexopt`
- ...? Please amend if needed..

**Comment by gplssm** [comment]
@birgits I suggest we do this along with the restructuring of the code basis

**Comment by birgits** [comment]
I restructured the configs. If you agree with it @gplssm you may close this issue, otherwise let me know if you find anything to be inconsistent or unclear.

**Comment by gplssm** [comment]
:+1:
