### ISSUE TITLE
Calculate line load

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#40]
In order to check for line overloading we need the line load (current). It is probably easiest to directly use pypsa results for this instead of calculating it in the results class.

**Comment by gplssm** [comment]
Some notes for myself:

* Voltage levels have to be taken from adjacent nodes of lines and transformers
* When a station is an adjacent node of a line, we cannot simply take the repr() because we have to distinguish primary/secondary side, see `mv_to_pypsa()`. A further note, lines itself always are connected to buses of adjacent nodes. For lines no extra bus is defined. How to proceed: build a mapping dict of lines <-> adj. nodes; get voltage levels for adj. nodes, build the average, assign it to the line label
* Similarly for transformers, no extra buses are defined here. Buses of the station are used. How to proceed: Build a mapping between transformer labels and associated station buses. Select v_res by station bus label and write under the label of each transformer contained in this station. Assignment to transformer names can be achieved by selecting results labeled under the station label an rename these labels
* Applies generally: Calculate the average of voltage levels at both sides of a line/transformer

**Comment by gplssm** [comment]
Current for transformers is not calculated as we compare rated power with apparent power from PFA.
