### ISSUE TITLE
Power flow grid reinforce interation: Update PyPSA data instead of new Network

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#44]
Lines and Transformers that were removed/ changed are returned by `extend_distribution_substation()` (and similar functions for lines) located in `reinforce_measures.py`.

Update the DataFrames `network.transformers` and `network.lines` by removed and added transformers/lines.

**Comment by gplssm** [comment]
@birgits should this include updating the eDisGo graph as well?

**Comment by gplssm** [comment]
Updating transformers in PyPSA data structure works well (as far as I know for now).

I have questions regarding updating the lines
1. How do you name the added lines? Do you take the id of the line that was already installed at that location? This would lead to trouble doing a PFA with PyPSA because the id is used to create the repr() which is used as index in PyPSA. The index items need to be uniquely named...
2. I need information about the adjacent nodes of each line in order to specify the buses the line is connected to. I see two options: (a) specify "the old line" (the line that is already installed at that location). Then I could access its neighbors and can construct the correct bus name. Or (b) you provided the adjacent nodes of each added line (or just its names), then I can use them directly.

**Comment by birgits** [comment]
> @birgits should this include updating the eDisGo graph as well?

Nope, this is done in the reinforce_measures module. The graph is only changed in case of over-voltage issues. The line is disconnected at 2/3 of the path to the node farthest away from the station and directly connected to the station. In all other cases the graph is not changed but the number of parallel lines is increased or a transformer added to a station.

> How do you name the added lines? Do you take the id of the line that was already installed at that location? This would lead to trouble doing a PFA with PyPSA because the id is used to create the repr() which is used as index in PyPSA. The index items need to be uniquely named...

There are three ways lines are added. Either the quantity is increased, then there is one entry in the equipment_changes['added'] dataframe; or the type is changed, then there is an entry in equipment_changes['removed'] specifying the old type and an entry in equipment_changes['added'] specifying the new type. When a line is disconnected and connected to the transformer it is similar to the previous case. There will be one entry in equipment_changes['removed'] and one entry in equipment_changes['added']. The ID of the new line is taken from the old line, but it is still unique since the old line does not exist in the graph anymore.  

> I need information about the adjacent nodes of each line in order to specify the buses the line is connected to.

You can get this information from the graph.

Please make sure to only update the changes for the last iteration step in equipment changes.
