### ISSUE TITLE
Calculate population density for MVGrids

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#57]
As it is calculated right now, the population density of the tested MVGrids is below 500 people/km². As @nesnoj pointed out in [here](https://github.com/openego/eDisGo/issues/45) a different approach should be taken if that is the case.

> EDIT: You may try it this way and if you realise that most of the MVGD show a pop. density of <500 we should test the other version (cum. area sum of all load areas) - you may create an issue to make sure we won't forget about it?

I don't understand why population density for MVGrids should be calculated differently? Area and population of the grids I looked at seem plausible.

**Comment by nesnoj** [comment]
> I don't understand why population density for MVGrids should be calculated differently?

What I've written is: If **most of** them..
I just wanted to avoid params getting lost somewhere in the code without having them checked a litte bit more...
Thanks for creating this issue!

I checked the DENA VNS again: On p63 they calculate pop. density using the municipality area, so you did it the right way. And since ~29 % show an EWD > 500 is does not seem to be too unrealistic.

BTW, you may obtain a pop. density distribution using:
```
WITH ranges AS (
    SELECT LPAD((ten*100)::text, 4, '0')||'..'||LPAD((ten*100+99)::text, 4, '0')||' EW/km2' AS range,
           ten*100 AS r_min, ten*100+99 AS r_max
      FROM generate_series(0,20) AS t(ten))
SELECT r.range, count(s.*)
  FROM ranges r
  LEFT JOIN grid.ego_dp_mv_griddistrict s ON population_density*100 BETWEEN r.r_min AND r.r_max
 WHERE population_density*100 < 10000
 GROUP BY r.range
 ORDER BY r.range;
```
Looks good :+1:
