### ISSUE TITLE
Retrieve PF results from PyPSA

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#7]
* Define results object that holds results from power flow analysis #14 (maybe in a DataFrame structure)
* Write a function to translates PyPSA results that are stored in DataFrames to the results object
* Provide access to results from each component of the grid (lookup in results object via ID)

**Comment by birgits** [comment]
For the line results we need to know the direction of P and Q!

**Comment by gplssm** [comment]
I will provide p0, p1 and q0,q1 (active, reactive power at each end of the line) which indicate direction of power flow. Is this enough for you? BTW, we do you need the direction?

**Comment by birgits** [comment]
I thought I'd need the direction to get the transformer load but as we discussed today the transformer load will be given in the results dataframes. So this is a reminder to you to assign the PyPSA results for the buses and the line representing the transformer in PyPSA  to the edisgo station object. 

We also decided to change the results object to have seperate dataframes/series for p, q and delta_u, instead of for nodes and edges (will be implemented by me). The dataframes will have a datetime index and the components as column names. (The station will appear in all three result dataframes.)

Another question that just came to mind - which p/q will we store in the results object. p/q0 or p/q1 or both?

**Comment by gplssm** [comment]
> Another question that just came to mind - which p/q will we store in the results object. p/q0 or p/q1 or both?

I suggest to only store p and q defined as p = max(p0, p1). Thus we ensure the line suits maximum current occurring on that line.

**Comment by birgits** [comment]
> I suggest to only store p and q defined as p = max(p0, p1). Thus we ensure the line suits maximum current occurring on that line.

Or maybe max(s0, s1)

**Comment by gplssm** [comment]
See [Docstring s_res](https://github.com/openego/eDisGo/blob/08438fc4d5428c6e5301a4780c3cac8bac8b1a35/edisgo/grid/network.py#L597-#L617) and [Docstring v_res](https://github.com/openego/eDisGo/blob/08438fc4d5428c6e5301a4780c3cac8bac8b1a35/edisgo/grid/network.py#L644-#L669) how to access results from power flow analysis.

If you find bugs or have a feature request. Re-open or open a new issue (whatever is more appropriate).
