### ISSUE TITLE
Reinforce HV/MV transformers

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#74]
HV/MV transformers need to be reinforced by eDisGo as well. Voltage level on secondary side can be neglected due to voltage controlled transformers. Apparent power needs to suit MV grid's generation capacity and peak load.

Get p, q values by
```
network.pypsa.generators_t['p']['Generator_slack']
network.pypsa.generators_t['q']['Generator_slack']
```

**Comment by nesnoj** [comment]
Trafos are properly selected now https://github.com/openego/ding0/commit/3f697b2aa49b61600a8f2f717edac75a433f3431 (fixed in dev as well as in dp0.3 branch). I did fuck it up in https://github.com/openego/ding0/commit/262b9309f5b3a69bf58d9d4186e969690ea01718 while messing around with the units (shame on me!).
Thanks for digging @mlinsenmeier 

PS: I did some checks on peak load data in the dp tables, seems to be correct..

**Comment by birgits** [comment]
I added a check and reinforce function for the hv/mv station. I also added P and Q results for the station to the Results object (Note: other than for mv/lv stations results are for the whole station instead of each transformer in the station.) 
I hope everything works properly. If not feel free to reopen.

**Comment by birgits** [comment]
I just found out that it does not yet work properly. For the pypsa export we need v_base but the voltage at the primary side is stored nowhere... I would put in a dummy value for now (100 kV). Should we introduce a new attribute for this at some point and retrieve the value from the database? @gplssm and @nesnoj what do you think?

**Comment by birgits** [comment]
Just kidding, we don't need it since MV station is not modelled in pypsa ;) I forgot about this for a while... I just had to make sure the new MV transformer is not added to the pypsa network and this fixed it.
