### ISSUE TITLE
Correct HV/MV transformer overloading check

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#94]
Currently, when the (n-1) criterion is checked for HV/MV transformers that maximum apparent power of all transformers of the substation is summarized. Due to the (n-1) criterion this is slightly wrong because one transformer must not be counted in this calculation. I suggest to exclude the second largest transformer from the sum of apparent power. This ensure a sufficiently large transformer is available for backup.

I think this issue does not apply for MV/LV transformer.

**Comment by birgits** [comment]
What you said is true for the load case; in the feed-in case the station load can be 100% since the (n-1) criterion does not apply for generators. Right now we only consider the feed-in case for the worst case analysis so I will postpone this to the next release when I will include the load case (see also #26).
I also talked to @boltbeard about this for clarification. How it is done in the real world is that there is a parallel transformer that can be connected when needed. So in case of a failure of one of the transformers the other one can be used and the demand of the consumers covered (that's why the allowed load of the transformers in the load case is 50%). The feed-in however can possibly not be transported to the HV grid in case of a failure and generators might have to be redispatched.

**Comment by birgits** [comment]
Fixed. See #26.
